const http = require('http');

let bio = "<p>Digital craftsman who believes code is poetry.</p> <p> Creating meaningful user experiences through thoughtful design and robust engineering.</p> <p>Passionate about the intersection of technology, art, and human connection.</p> <p>Forever student of the web.</p>";

const server = http.createServer((request, response) => {
    if(request.method === "PATCH"){
        let newBio = '';
        request.on('data', (chunk) => {
            newBio += chunk;
        });

        request.on('end', () => {
            console.log(`Original bio: ${bio}`);

            bio += newBio;

            console.log(`New bio: ${bio}`);

            response.writeHead(200, {'Content-type': 'text/html; charset=utf8'})
            response.end('Bio Updated!');
        });
    }
    else if (request.url == '/'){
        response.writeHead(200, {'Content-type': 'text/html; charset=utf8'})
        response.end(bio);
    }
    else{
        response.writeHead(404, {'Content-type': 'text/html; charset=utf8'})
        response.end('<h1> 404 Not Found </h1>');
    }
});

server.listen(3000, () => {
    console.log('http://localhost:3000/');
});

//instructions to update bio: curl -X PATCH http://localhost:3000 -d "<p> Oh..... It's generated by AI!</p>"  in your terminal